### ISSUE TITLE
Please consider not showing in the 404 log any valid 410 redirects

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#1024]
Please consider not showing in the 404 log any valid 410 redirects.

Or at the very list change the backgroudn of the rows. Somethign to indicate they were redirected as 410.

**Comment by terryheff** [comment]
Suggestion:

Instead of removing 410s from the display, why not simply label the response code (301, 410 etc.) in the display. Personally, I would find that more informative.  

As an aside, I notice that the 410 hit count is not working in the list of redirections. All of the 410s I created show hit count of zero when I know that many hits have occurred - any comments on that?

Thanks and regards
