### ISSUE TITLE
Priority not working

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#1163]
From [wordpress.org](https://wordpress.org/support/topic/redirect-priority-does-not-work-for-me-it-used-to/):

> I have a basic regex redirect from “/checkout/.*” to “/” (homepage), with Priority set to 5. It works.
>
> Now, I want to allow a specific checkout URL to bypass the above-mentioned redirect. So, I am adding a new redirect like this,
>
> “/checkout/?id=xxxxxxx&param=yyyyyyyyyy” (this is not regex), with Position 1 and “When matched” value equaling to “Do nothing”. This does not work.
>
> Some weeks ago, while still having the previous plugin version, it used to work.
>
> Also, I have reproduced this behaviour on my localhost development environment.

**Comment by MBSchneider** [comment]
+1 on this!

**pos 1000** regex with `\/college-salary-report-2014.*` points to `/college-salary-report`

**pos 9** URL `/college-salary-report-2014/choosing-a-major/popular-jobs-by-major/computer-science-and-math` points to `/college-salary-report/common-jobs-for-majors/computer-science`

Expected behavior would be for the second redirect to take precedence, but it's not.

test URL: https://v2-wp-staging.payscale.com/college-salary-report-2014/choosing-a-major/popular-jobs-by-major/computer-science-and-math

**Comment by ckaklamanos** [comment]
Hello, I am the original poster of the issue on wordpress.org.

https://wordpress.org/support/topic/redirect-priority-does-not-work-for-me-it-used-to/

Today, I was trying to make this work, using the latest version of the plugin. The problem still exists. 

Prior to updating the plugin, it was working just fine.

Can you please confirm that the issue still exists?

And, is there any way that we can help with code or testing?

Thanks in advance.

**Comment by johngodley** [comment]
It's still active, but I haven't looked at it yet. I will post to this thread when any progress is made.

**Comment by johngodley** [comment]
I'm trying this with the current (unreleased) version here on Github and am unable to reproduce the problem. It may be fixed by an earlier version, but otherwise it should be fixed by the upcoming 5.0 release.
