### ISSUE TITLE
Feature Request: Import/Export position

### ISSUE THREAD

**Issue by rodgerzeisler** [johngodley/redirection#1189]
Add "pos" for position as an exported/imported column.

The current list of columns that can be exported/imported are:
- source
- target
- regex
- type
- code
- match
- hits
- title

**Comment by johngodley** [comment]
Import/Export of what? The JSON format is meant as the canonical representation of your data. The CSV format is not

**Comment by SherylHohman** [comment]
It is not clear that only the JSON export is *supposed* to save all the data.  
Also, CSV is easiest to work with for adding a lot of redirects.  

When I deleted everything, then re-imported my updated CSV, I was also disappointed to discover that certain fields were "reset".   
Personally, I'd like to be able to add comments, position, etc to my rules using a spreadsheet, when making a massive site change.  
I suppose there is a tool that can convert CSV to JSON.. I'll look for that.  

For the general population, though, many of whom may not even know what JSON is,   
A little blurb stating that JSON export saves ALL misc data,  
whereas CSV only saves the most important bits, might help with confusion or surprises.   

Otherwise, it's assumed that all export methods save all the data.  
Especially appreciated if the user thought CSV export was how they should "backup" their data.   
Just a thought.

**Comment by johngodley** [comment]
I've added some notes to the import/export page explaining about JSON and CSV. Note that JSON is the default export format.
