### ISSUE TITLE
Dynamic Redirect that excludes 404s

### ISSUE THREAD

**Issue by hartey11** [johngodley/redirection#135]
Hi,

I'm building a site that needs to redirect all single posts from a custom post type to a page as a pass through.

I've set this up using a wildcard "/work/(.*)" to redirect to "/work" however if I type in random characters these also get redirected. Ideally I need valid pages to redirect and invalid ones to a 404 page.

How do I dynamically add a redirect for all single posts to a page that doesn't include invalid pages such as "/work/dsfdasf" as well?

**Comment by daniel-barrows** [comment]
Can you clarify what you mean by "valid"? Do you mean you have several existing pages like /work/some and /work/more, and you want to redirect them to another page instead of their existing pages? However, you don't want /work/arbitrary to also redirect, but to return a 404 instead.

This seems like an unusual use case, and is unlikely to be implemented in this redirection plugin. I suggest your best bet is to get a list of existing pages via your sitemap and just use some RegExps to convert that into a form suitable for adding directly to your .htaccess file.

**Comment by johngodley** [comment]
Closing for now, but please reopen with more information
