### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by erdalurall** [johngodley/redirection#1448]
```
Plugin: 3.7.3
WordPress: 5.0.3 (single)
PHP: 5.5.38
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: http://ozdalgroup.com.tr/wp-content/plugins/redirection/redirection.js
REST API: http://ozdalgroup.com.tr/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details

**Comment by infostreams** [comment]
First of all, @johngodley - thanks for the great plugin! It's really the best redirection plugin I've come across.

However, I do have the same issue. I have a multisite setup, and whenever I add a site to this multisite and then enable the Redirection plugin and do the setup, I get the same error:

```
Plugin: 4.3.1
WordPress: 5.2.2 (multi)
PHP: 7.2.7
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: http://mysite.magazines.localhost/wp-content/plugins/redirection/redirection.js
REST API: http://mysite.magazines.localhost/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

I looked at the link you provided and couldn't find the answer to this error there.

The issue seems to be that it cannot load the "/wp-json/redirection/v1/plugin/database" route. If I try to open it in a browser, I get a 404. If I open it in [Postman](https://www.getpostman.com/downloads/) so that I can do a proper POST request, I get a 404 as well.

The "/wp-json/" URL is returning a large chunk of JSON, and during the plugin setup process the plugin itself also indicates that the REST API is working 100%.

However, if I manually change the url to '/index.php?rest_route=/redirection/v1/plugin/database' it does load. But I can't change the REST API in the initial setup (don't know why), and I can't expect my users to do these kind of things either.

Anyway, I managed to work around the issue by 

a) Setting the default multisite theme to my own theme and then 
b) Adding the following code to my ```mytheme/functions.php```

```php
/**
 * Fixes the 404 error that you get when enabling the 'redirection' plugin.
 *
 * (Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method",
 * "data":{"status":404}}).
 *
 * Only works if 'mytheme' is your theme (which isn't the case for new sites), so make sure that the
 * default theme for new sites is 'mytheme'. Add this to wp-config.php:
 *
 * define( 'WP_DEFAULT_THEME', 'mytheme' );
 *
 * @param array $settings The default settings.
 *
 * @return array The default settings with adjusted rest API location.
 */
function mytheme_rest_api( $settings ) {
	// see plugins/redirection/redirection-settings.php - '1' means "use the /index.php?rest_route=/ route".
	$settings['rest_api'] = 1;
	$opts                 = get_option( 'redirection_options' );

	if ( empty( $opts['database'] ) ) {
		// create the tables. The plugin setup is buggy so we circumvent it. Sorry.
		global $wpdb;
		require_once dirname( __FILE__ ) . '/../../plugins/redirection/redirection.php';
		$db = Red_Database::get_latest_database();
		$db->create_tables( $wpdb );

		$settings['database'] = REDIRECTION_DB_VERSION;
	}

	return $settings;
}
add_filter( 'red_default_options', 'mytheme_rest_api', 10, 1 );
```

I know that's a terrible hack, but like this I can enable the plugin and skip the whole setup screen that has been causing me problems every time I add a new site to the multisite installation. More importantly, users can now enable the plugin without filing a support ticket. Hope this is of help to someone, and that @johngodley
