### ISSUE TITLE
Would be nice to be able to create redirects as a bulk action in the 404 tab

### ISSUE THREAD

**Issue by natalipro** [johngodley/redirection#148]
Right now the only bulk action available is delete. I recently migrated a site to a totally new structure and get lots of 404 that I want to redirect to 410.

Thanks

**Comment by johngodley** [comment]
How would a bulk create redirect action work?

**Comment by Lewiscowles1986** [comment]
AJAX post to REST or AJAX url; clear form inputs (if needed get another nonce from AJAX). I can look into it as it's not tonnes of code (move existing code for saving into public method and pass input as params). But my last PR won't pass due to a problem with 4.4 so I'm not sure that this PR would be accepted either.

**Comment by johngodley** [comment]
I didn't mean how would it work technically, but how would it would look to the user and what options are available.

**Comment by Lewiscowles1986** [comment]
:man_shrugging: IDK :christmas_tree: :santa: :gift: :+1:

**Comment by lucanos** [comment]
I would suggest the following:

* Group 404s based on the URL visited (as it will not be uncommon for multiple visits to be affected by the same issue).
* Show the count of the 404 logs per URL (and allow sorting by same).
* Show "X IP Address(es)" to indicate how many IP addresses are affected by the same error.
* When a Redirect Rule is applied for the affected URL, mark all associated log entries as Resolved.

**Comment by just-us** [comment]
And also an auto delete function once the redirect has been affected would be nice.

**Comment by just-us** [comment]
Another way would be to include it in the Bulk Actions in a similar way to the Posts or Pages menus. Add Redirection in the Bulk Actions drop down so you can select all of the 404s that you wish to redirect to. You can already order the URLs by clicking on the Source URL tab at the top so that would sort all the URLs into one pile that you could tick and then group edit.

**Comment by johngodley** [comment]
Bulk creation added in #1232
