### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by LETHIHONG** [johngodley/redirection#1677]
```
Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://honglethi.com/wp-content/plugins/redirection/redirection.js
REST API: https://honglethi.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by tombond999** [comment]
Same issue

**Comment by johngodley** [comment]
Please follow the instructions show inside the warning message in the plugin.

**Comment by topraf** [comment]
Having a similar issue since 2 months. Using Cloudflare (i followed the instructions to clear cache   disable cache of plugin), WP Rocket (cleared cache several times) & Stackpath - also cleared cache. Still, seems impossible to load the newest version of the plugin. Might be linked to a server-side caching? Seeing the number of people having this issue, would be cool to get a workaround. thanks

**Comment by johngodley** [comment]
Please logout, clear your caches, and login again. Closing for now
