### ISSUE TITLE
cannot access plugin setting

### ISSUE THREAD

**Issue by boussif** [johngodley/redirection#175]
I got this error message when i click setting :"You do not have sufficient permissions to access this page."
I’m administrator.

**Comment by boussif** [comment]
wordpress version 4.7
redirection version : 2.5

**Comment by johngodley** [comment]
I think this may be caused by something else other than the plugin. Have you tried some of the solutions for that error message?

https://stackoverflow.com/questions/13815461/you-do-not-have-sufficient-permissions-to-access-this-page-without-any-change
http://ghaoui.com/blog/2011/12/wp-solve-you-do-not-have-sufficient-permissions-to-access-this-page/

**Comment by johngodley** [comment]
Closing for now. Please reopen if you have more details
