### ISSUE TITLE
Add a deleted post to 410 redirect option

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#2066]
Expand the 'monitor deleted post' feature to create a 410 error, as well as a redirect.

**Comment by mcmito** [comment]
Now that would be something. This practice has been recommended for quite some time. As long as a post is in the trash, the website could send the actually correct message to Google: "The post is gone for ever" instead of "oops, I couldn't find anything". This would also make it easier to remove pages from the Google index.

**Comment by johngodley** [comment]
Moving to 3349
