### ISSUE TITLE
RFC: Updating GitHub template (proposal for a PR from me)

### ISSUE THREAD

**Issue by danielfdickinson** [johngodley/redirection#2750]
* After [writing a semi-formal test case](https://github.com/johngodley/redirection/issues/2744#issuecomment-774535801) for an issue I was having, some enhancements to the issue template occurred to me
* Since I used example.com rather than a live website for that test case, it occurred to me that being more detailed in the request for 'Steps to reproduce' might be beneficial in requesting users use domainX.example.com (which I didn't initially think of) to avoid the appearance of the steps being used to do link spam
* (if you wish I can go back and edit all my comments to use example.com type URL).
* In addition, instead of steps to reproduce, I think it would have helped focus my brain in the right direction to request 'detailed steps for automated testing for this issue' at least for issues believed to be in the plugin/server side rather than a client issue.
* If you are interested, I could try and write a new template (well since GitHub is [yammering about switch to the new issue workflow](https://docs.github.com/articles/about-issue-and-pull-request-templates) I guess it'd be case of switching flows and then updating the template) that would capture this and other improvements to the request for information.

Obviously not as wordy as this proposal.

What do you think?

**Comment by danielfdickinson** [comment]
Actually, given how many attack attempts I've seen since posting the ticket (now that I've looked at the logs), it seems that updating the template to suggest example.com and example.net domains instead of real domains for the user's own protection might help reports make the effort.

**Comment by johngodley** [comment]
Real URLs are the most useful things provided in reports, and many problems can be solved just by having these.

A website is by design a public entity. They are meant to be linked to, and don't require hiding for protection. I almost always have to ask for a real URL if a fake one is provided, which increases the amount of work required.

The majority of people barely read the Github template, and it has a nominal effect on reports (it often just gets left in the report). By all means create a PR, particularly if it involves simplifying the text.
