### ISSUE TITLE
Redirect if a specific parameter does not exist

### ISSUE THREAD

**Issue by vatsalmtrivedi** [johngodley/redirection#3379]
### Summary

I'm trying to setup a redirect if a specific parameter does not exist. 

I DON'T WANT this to redirect, but everything else to redirect to the main site.
https://subdomain.abc.com/?check_connection=1 redirects to https://www.abc.com/

### Actual Behavior

Current redirect setup
https://subdomain.abc.com redirects to https://www.abc.com/
Also
https://subdomain.abc.com/?check_connection=1 redirects to https://www.abc.com/

### Steps to reproduce

Enter either URL they will both redirect

### Environment

Wordpress

**Comment by johngodley** [comment]
You can use a regular expression:

https://redirection.me/support/redirect-regular-expressions/

It should be possible to pick an expression that doesn't match the parameter.

**Comment by vatsalmtrivedi** [comment]
Thanks for your help

I sort of got it working. I need to exclude multiple scenarios form redirecting 

This is what I tried 

check_connection=1  used /(?!check_connection), order 4

AND FOR ANOTHER EXCLUSION

/wp-load.php?import_key=3AgbUl96&import_id=166&action=cancel

I tried /(?!import_key) on separate redirect order 3

order 3 does not work

**Comment by services4smb** [comment]
I have been trying to solve a similar issue and I ended up adding two redirections.
If URL = https://subdomain.abc.com/page?check_connection=1 (when matched: **do nothing**; position: **0**) 
If URL = https://subdomain.abc.com/page (when matched: **redirect to url** with http-code: **302 - found**; position: **1**) redirect to https://subdomain.abc.com

I'm not using Regex (tried unsuccessful) but the bit strange part is that redirection doesn't seems to match entire URL, because below url's are matched equal:
https://subdomain.abc.com/page?check_connection=1
https://subdomain.abc.com/page?connection=True

**Comment by johngodley** [comment]
@services4smb I don't understand what problem you are describing. It will be better to start your own issue.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
