### ISSUE TITLE
Updated and now broken

### ISSUE THREAD

**Issue by ChristianMorassutti** [johngodley/redirection#3420]
Hi I updated this plug in and now it is givoing me this erroe. I have reset cahce on site and in browser, and restarted all programs. 

This is a really important client site so time is key. 
We use this app with no issues ever and reallly do not wish to change. 

Thanks 

Christian

---

WordPress: 6.0.2 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
JavaScript: https://sawilsons.com/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://sawilsons.com/wp-json/
Query: ?page=redirection.php&sub=options
Buster: 5.3.2 === 5.3.4

**Comment by johngodley** [comment]
The cache has not been cleared.

Load this file and note how it says 5.3.2

https://sawilsons.com/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08

It should say 5.3.4

**Comment by ChristianMorassutti** [comment]
I am using WP Rocket, I cleared the cache and all un used CSS. I cleared browser cache as well. 

When you say "load this file" do you simply mean click on that link? when I do it serves all the code minified. Is it supposed to do that?
![Screen Shot 2022-09-19 at 2 09 13 PM](https://user-images.githubusercontent.com/17956116/191084870-192770a1-ef82-4b7c-8b1c-5cc343ce4cf6.png)


 Sorry if I am not understanding correctly. 

So why is this error showing? Because I have not cleared which cache?
![Screen Shot 2022-09-19 at 2 07 09 PM](https://user-images.githubusercontent.com/17956116/191084944-c8b4c5f0-58df-4322-b497-5df43571f509.png)

**Comment by ChristianMorassutti** [comment]
If its caching how do I check that the plug in is still working? with this error I cant see any of my redirections?

**Comment by johngodley** [comment]
Yes it is supposed to do that. The version number is shown at the top, and it says 5.3.2, which is incorrect for the version of the plugin you have installed.

The error is shown because the plugin detects this situation. You will need to fix the problem in order to use the plugin. I cannot tell you how to do that - it is specific to your site and not a problem with the plugin itself.

Your redirects are still redirecting and are unaffected.

You may have more than one caching system on your site. You may also want to check the file manually and see if it really does contain the 5.3.4 code. If it does not then you might not have installed or upgraded it properly.

**Comment by ChristianMorassutti** [comment]
Oh okay I do see the line in the file, in Cpanel. 

K Ive adjusted some cache settings, If you say the redirects are working still, if I leave this as is until the cache expires is that okay?

**Comment by johngodley** [comment]
Sure. It's used by the admin interface only.
