### ISSUE TITLE
How to remove canonical urls on pass throughs

### ISSUE THREAD

**Issue by albertdiones** [johngodley/redirection#349]
### How to remove canonical urls on pass throughs?

My client asked me to copy hundred pages to some URLs that are originally 301 redirects, they are thinking that this would help SEO instead 301s.

I used your plugin's pass through feature but the canonical link tag is still pointing to the original pages. Is there a good way to get around through this? I want the canonical link tag removed or point to the source url instead of the target url.

### Actual Behavior

link[rel=canonical] tag points to target page

### Steps to reproduce

1. Add a passthrough rule on redirection plugin
2. Visit the new page
3. check the source code
4. shows the original page (target url)

### Environment

Wordpress Version 4.8.1 Redirection 2.7.3

**Comment by johngodley** [comment]
I know it's a while since you posted this and I've thought about whether this is something the plugin should handle. Currently I think it's a little beyond what Redirection should provide.

Instead if you look at the list of hooks [here](https://github.com/johngodley/redirection) it should be possible to achieve what you want by adding your own PHP code that listens for when a passthrough redirect occurs and then changing whatever needs to change in WordPress for the canonical URL to also be updated
