### ISSUE TITLE
Unable to make request due to browser security. This is typically because your WordPress and Site URL settings are inconsistent, or the request was blocked by your site CORS policy.

### ISSUE THREAD

**Issue by narasimma-webdev** [johngodley/redirection#3505]
Plugin: 5.3.5 4.2
WordPress: 6.1.1 (single)
PHP: 8.0.25
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
JavaScript: https://revatureusa.wpengine.com/wp-content/plugins/redirection/redirection.js?ver=5.3.5-f0dac5b2b3267cd737c1a679e4c1fac3
REST API: https://revature.com/wp-json/
Query: ?page=redirection.php&sub=log

Error: Failed to fetch

I have tried deactivate all plugin and checked its getting error as Failed to fetch Unable to make request due to browser security. This is typically because your WordPress and Site URL settings are inconsistent, or the request was blocked by your site CORS policy. can you help on this

**Comment by johngodley** [comment]
> This is typically because your WordPress and Site URL settings are inconsistent

https://revatureusa.wpengine.com https://revature.com/ - these look different?

**Comment by dsp76** [comment]
@johngodley does it mean, it won't work when WordPress URL != SiteURL?

**Comment by johngodley** [comment]
It means your browser is blocking the request to your REST API because of the difference in URL. This is how WordPress works and is not caused by the plugin itself. Changing the URLs to be the same will fix the problem (and maybe fix other problems caused by a mixed domain). Do you need the WP Engine one there? It doesn't seem like the best thing to have.
