### ISSUE TITLE
Nearest Match?

### ISSUE THREAD

**Issue by JDumire** [johngodley/redirection#409]
Hello!, I just changed the permalink structure for my blog posts from: https://simplycolorlab.com/%postname%/   to: https://simplycolorlab.com/posts/%postname%/
I am trying to figure out if this plugin will allow nearest match to let links that are with old address  make it successfully to new address?

Currently if i type in the old address it will go to the correct new page, however, if one clicks a link with old address i get a 404. 

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Environment

browser: Chrome 
browser version: 61.0.3163.100 
version of WordPress: 4.8.2
Redirection plugin version: 2.7.3

Thanks in advance

**Comment by johngodley** [comment]
Redirection does not do any matching of permalinks. You can use a regular expression match instead.

**Comment by JDumire** [comment]
thanks John for your answer. What would that look like exactly? Something like below? or can you direct me to info please?

https://simplycolorlab.com/%postname%/
to
^/posts/.*

**Comment by johngodley** [comment]
A permalink structure is not the same as a regular expression - you won't be able to use it in a redirect.

Because your original permalink structure is so generic you may find that a regular expression ends up catching more than what you want, and it may not be possible to use one. You have two choices here:
- If your website has no other URLs that match `/%postname%/` then a regular expression such as `/(.*)/$` => `/posts/$1` would work
- If your website has other URLs that would also match then you will need to redirect each individual post

**Comment by johngodley** [comment]
Closing for now, please reopen if needed.
