### ISSUE TITLE
Redirect 301 goes 404

### ISSUE THREAD

**Issue by erimae** [johngodley/redirection#516]
I created some type 301 redirects for example:
Source URL: /test/
Target URL: https://www.myurl.com/newtest/

### Actual Behavior
When i visit the old url https://www.myurl.com/test/ it wil not redirect to https://www.myurl.com/newtest/ but it will show a 404

I use Safari and Firefox, deleted the cash . Latest WP and Redirection version

**Comment by johngodley** [comment]
Did you create the redirects using the WordPress module or Apache?

Can you include the real URLs here?

**Comment by erimae** [comment]
I created them with the WP module, see screenshot:

![schermafbeelding 2017-11-08 om 08 33 29](https://user-images.githubusercontent.com/33467367/32536634-8d8ad1e0-c45f-11e7-90bd-e5d13780de8a.jpg)

**Comment by AytacM** [comment]
Hi, same problem here. Latest WP and Redirection version.
My old website was static and it had /eng/ subdirectory for english language files. The root directory had original language files and those redirections work just fine. The only problem is the english sub-directory files' redirection.
I am not sure if it's relative but in the resulting 404 page, the red arrow on the image shows only one slash"/" http:/ma-er.com... although I double checked the target url is http://ma-er.com....
![404 message](https://user-images.githubusercontent.com/33518907/32608527-a8f834f4-c56d-11e7-8af2-f71537b5bcd5.png)

I created them with the WP module, see screenshot:
![opera snapshot_2017-11-09_162727_ma-er com](https://user-images.githubusercontent.com/33518907/32607726-f345ace2-c56a-11e7-8a45-61a083b4e250.png)

**Comment by johngodley** [comment]
@AytacM You don't need the regex option checked for that redirect.

I tried creating the exact same redirect and it worked fine for me. This leads me to believe that something else running on your server is affecting the target.

If possible could you try disabling all other plugins and then see if that changes anything?

**Comment by AytacM** [comment]
Hello johngodley,
I disabled all other plugins and tried it. Nothing changed.

**Comment by johngodley** [comment]
Shame. Would it be possible to get access to your WordPress to see if I can find anything out? If that's ok then you can contact me through the support page in the plugin.

**Comment by AytacM** [comment]
Okay, I sent you an email with the user details of my site.

**Comment by johngodley** [comment]
@AytacM thanks, received and investigated. The issue is because all your redirects have the regex checkbox enabled when they don't need it, and this causing strange side-effects.

In this specific instance what is happening is that you are trying to access `/eng/06-yag-cubugu.html` and are expecting to match the redirect for `/eng/06-yag-cubugu.html`. However, you also have a redirect for `/06-yag-cubugu.html` that because it has the regex option enabled is matching the end of the URL first:

/eng<strong>/06-yag-cubugu.html</strong>

Also because it is a regex the match is applied to the target and you end up with the first part of the original URL + the target URL:

`/eng` +  `http://www.ma-er.com/konnektorler/` = `/enghttp://www.ma-er.com/konnektorler/`

If you disable regex then the redirect works fine.

So, all of that to say that you should disable regex on everything unless it really is a regex.

@erimae it might be worth checking your redirects to see if the same applies.

**Comment by AytacM** [comment]
@johngodley, thank you for your detailed answer. I appreciate it.

I disabled regex but the same issue continues. Did you manually check the old link if the redirect works? Am I missing something? I also tried the old link with a proxy in case of cache issue but it didn't help.

**Comment by johngodley** [comment]
Yes, your link is working fine now:

```
curl -v -I http://www.ma-er.com/eng/06-yag-cubugu.html                                                                                                                                master
*   Trying 94.73.149.95...
* TCP_NODELAY set
* Connected to www.ma-er.com (94.73.149.95) port 80 (#0)
> HEAD /eng/06-yag-cubugu.html HTTP/1.1
> Host: www.ma-er.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 10 Nov 2017 06:35:00 GMT
< Server: Apache
< X-Powered-By: PHP/7.1.11
< Expires: Fri, 10 Nov 2017 07:35:01 GMT
< Cache-Control: max-age=3600
< X-Redirect-Agent: redirection
< Location: /en/connectors/
< Content-Type: text/html; charset=UTF-8
```

Note how the `location` is the correct URL. Try clearing your browser cache.

**Comment by AytacM** [comment]
Oh, now I can see. Thank you for your help, John. I appreciate your time and effort.

**Comment by erimae** [comment]
Strange... I never had the regex option checked. So I checked this option and deleted url before the / and now it work's A Okay !
