### ISSUE TITLE
Feature request: Display more details in redirection list

### ISSUE THREAD

**Issue by galbaras** [johngodley/redirection#552]
Redirections have important attributes, such as "regex", which are not visible unless a redirection is opened. In fact, there is a lot of room on the page to list additional columns, like both source and destination, the type, etc.

Columns should be available in the screen options for selection, and when checked, they should appear on the page for the user to see them and sort by them, just like posts, pages or products.

**Comment by Beee4life** [comment]
+1 for this. I would like to see a column for the group in which it's listed for example.

**Comment by SherylHohman** [comment]
I would also really like this feature!
Visual feedback that a rule is/isn't marked as regex would be particularly helpful, as it is very easy to write a regex rule, then forget to mark the [x]regex box.   

Personally, I'd prefer if the regex box was to the left of the source url, rather than the far right.  Then I would mark it before writing regex, and also see that it's marked or unmarked right away when the rule is opened up.   

As the layout currently is, we are encouraged to write the rule first, then _remember_ to look for and mark  the box at the other side of the page .  When the rule is closed, there is no column, or other visual feedback (such as color), to indicate whether the rule is indeed being processed as regex.

I would also really like to be able to sort.

Semi-related, personally, I would also like to see both source url and title, when a title is supplied.  This is particularly useful when a complex regex is entered.  As a work around, I copy the source url into the title field. Then write my comment after that. It's ugly, and means I must edit in two locations, but It's helpful to always be able to see the match rules.
The other reason showing both would be helpful, is that only source url shows strikethrough when a rule is disabled.  Hence, if I disable a titled rule, there is no visual feedback, unless I _also_ add a note to my title (ie "DISABLED").  Then, I must remember to edit my title when enabling the rule.  
I did submit a PR to add strike-through text to the title, when its rule is disabled.  If both url and title fields are visible, strike-through would not needed for the title.

I am willing to contribute to this PR, if you are open to it.  
I just need to get my environment set up properly.   My local clone is throwing errors.

**Comment by galbaras** [comment]
As per https://wordpress.org/support/topic/regex-indicator-in-lists-and-greedy-patterns/, just wanted to add the ability to detect "greedy" regular expressions.

One simple way is to display the "regex" indicator as a column, or somehow style regular expression redirections differently. A better way is to allow filtering redirections by their regex setting. Then, patterns can be examined without wasting time opening and closing them.

Of course, the ideal solution would be a way to list only "greedy" patterns. I'm not sure what these are, but if it's a matter of not having "^" at the start of a regex pattern, they should be easy enough to spot.
