### ISSUE TITLE
regex eating %0A (URI-encoded newlines)?

### ISSUE THREAD

**Issue by FrankVahid** [johngodley/redirection#608]
### Summary

Possible bug: For a regex using (.*), the replaced text is missing %0A's (newlines) from a URI-encoded string

### Actual Behavior

I'm using Redirection with regex to pass along a query string: 
Source URL: /subdir(.*)
Target URL: https://otherdomain/index.html$1

My query string is the output of encodeURI. So I might pass this: 
http://mydomain/subdir?code=integer%20x%0Ax%20=%205&input=%20

However, the target URL ends up being this: 
http://otherdomain/index.html?code=integer%20xx%20=%205&input=%20

The %0A is missing from the middle, which is the encoding of a newline character. 

I'm not a regex expert so it's possible I'm missing something, but is it possible that the regex implementation is somehow eating the %0A? 

### Steps to reproduce

Enter URL in browser: 
http://mydomain/subdir?code=integer%20x%0Ax%20=%205&input=%20
Result is:           
http://otherdomain/index.html?code=integer%20xx%20=%205&input=%20
The %0A is missing.

### Environment

I'm using wordpress.com. Just installed the Redirection plug-in today (can't find the version number).

**Comment by johngodley** [comment]
It seems this is caused by WordPress itself in the `wp_sanitize_redirect` function. WordPress thinks that those characters are invalid, and strips them away from URLs. The code doing this is:

https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/pluggable.php#L1225

I'm not sure of the reasoning behind this, but I would be hesitant to change the behaviour inside Redirection in case it causes a security issue.

You may be able to make a local modification to `wp_sanitize_redirect` (it is pluggable, so can be defined locally without modifying core WordPress files) to not strip the character.

**Comment by FrankVahid** [comment]
Excellent info. Thanks very much. --Frank
