### ISSUE TITLE
Redirection problem

### ISSUE THREAD

**Issue by eniss4y** [johngodley/redirection#714]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

My template is Kallyas Theme. 

### Summary

I have a error code "cURL error 28 : Operation timed out after 5001 milliseconds with 0 bytes received" (like in attachment).

### Actual Behavior

In addition, "Wordpress Rest API" and "redirection routes" tell me "problem" (like in attachment). 

### Steps to reproduce

Just go to the "Redirection" plugin in back-office Wordpress and I've this problem. I have tried magic correction but nothing at all.

### Environment

Google Chrome last version, Wordpress 4.9.2 and Redirection plugin 3.1.1. 

Thank you in advance. 

Regards, 
Yas
![redirection problem](https://user-images.githubusercontent.com/36007482/35636644-204b1d34-06b2-11e8-8576-264c0701563c.png)
![redirection](https://user-images.githubusercontent.com/36007482/35636645-20648a62-06b2-11e8-917d-3ed38e2d2314.png)

**Comment by johngodley** [comment]
Does the plugin work on other pages?

**Comment by johngodley** [comment]
The timeout error is because on the support page the plugin tries to check that your REST API is working. For some reason this is timing out on your server after 5 seconds - your server is taking longer than 5 seconds to respond. If the plugin is otherwise working then this in itself isn't a problem and you can ignore the error message here.

It is strange that the request would take so long though. Does it take a long time for Redirection to show any information?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
