### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Dusza** [johngodley/redirection#810]
```
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
JavaScript: http://metabolic5.staging.wpengine.com/wp-content/plugins/redirection/redirection.js
REST API: https://metabolic5.staging.wpengine.com/wp-json/

Error: NetworkError when attempting to fetch resource.

Error: NetworkError when attempting to fetch resource.
```

**Comment by johngodley** [comment]
You have a http and https URL there. What are your URLs on the Settings > General page?

**Comment by Dusza** [comment]
@johngodley https://metabolic5.staging.wpengine.com (both for site and wordpress URL)

**Comment by johngodley** [comment]
The problem is likely caused by the different between the http JavaScript file, and the https REST API. The JavaScript file is loaded by `plugin_dir_url`, and this is something set by WordPress. If you say they are both https on the General settings page then I'm not sure what else could be changing it.

**Comment by Dusza** [comment]
I’ll contact wpengine since this is hosted with them

**Comment by Dusza** [comment]
@johngodley issue solved.   there were some transient database entries which have been cleaned up.  no more errors.
