### ISSUE TITLE
Regular expression syntax

### ISSUE THREAD

**Issue by Castillealma** [johngodley/redirection#815]
I need help to create a group of redirection by a regular expression syntax !

### Summary

I need help to create a group of redirection by a regular expression syntax !
I have change the name of my portfolio so 
"http://castillealma.com/old-name/..."
became
"http://castillealma.com/new-name/..."

### Actual Behavior

With the regular expression syntax I have made a redirection like that : 
http://castillealma.com/old-name/(.*)
became
http://castillealma.com/new-name/$1

It works **BUT**

### Steps to reproduce

When i have an URL like that with 2 "underfolder": http://castillealma.com/old-name/#1/#2/

I have try to do this
http://castillealma.com/old-name/(.*)/(.*)/
became
http://castillealma.com/new-name/$1/$1/

**It does not  WORK .....** **## PLEASE HELLLLLLPPPPP**

### Environment

Google chrome,  version of WordPress 4.9.4 and Redirection plugin  "Rederiction"Version 3.2 | Par John Godley.

**Comment by johngodley** [comment]
You can use something like https://regex101.com/ to test and develop regular expressions. With that you will see that in `/old-name/(.*)/(.*)/` the first `(.*)` is grabbing `/#1/#2`. This is because `.*` is greedy - it will match everything. You can use `.*?` for a non-greedy match that will only match until the `/` that follows it. This should solve your problem

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
