### ISSUE TITLE
[Feature Request] Deal with UTMs

### ISSUE THREAD

**Issue by PierreLechelle** [johngodley/redirection#89]
Thanks for this amazing plugin. I'm using it on all my websites.

We ran into a small issue today while changing most of our URLs through automatic redirection. Some of our old URLs were tagged with UTMs (/blog/aaa?utm_campaign...). The plugin didn't handle these redirections and showed a 404.

It'd make sense for the plugin to handle these redirections by default (especially for automatic redirections).

(We fixed the problem by using regex for now)

**Comment by ckeim** [comment]
Hi Pierre,

Do you have an example of how to do this with regex? I'm having the same issue.

Thanks so much!

**Comment by jtbayly** [comment]
Is this feature planned for implementation, by chance? Or can anybody suggest an alternate method to fix the problem? We're really struggling with this issue.

**Comment by johngodley** [comment]
I know it's a long time since this issue was created. It was always possible to use a regular expression to handle query parameters, and with 4.0 alpha you can now do this even easier. I'll mark this as 'done' as I don't think anything else is needed.

https://github.com/johngodley/redirection/releases/tag/4.0-alpha-1

**Comment by johngodley** [comment]
This isn't really a support forum and regular expressions are beyond the scope of Redirection itself. You can find more information regarding Redirection at https://redirection.me/support/redirect-regular-expressions/ and there are a lot of regular expression tutorials on the internet
